# This is a basic workflow to help you get started with Actions

name: Push PDF on release

# Controls when the action will run.
on:
  # Triggers the workflow on release
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install font
        run: |
          sudo mkdir -p ~/.local/share/fonts/
          wget -c https://github.com/alerque/libertinus/releases/download/v7.040/Libertinus-7.040.tar.xz -O - | sudo tar -xJ -C ~/.local/share/fonts/
          fc-cache -rv

      # Compile with latexmk and xelatex
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ahale.tex
          latexmk_use_xelatex: true

      - name: Upload PDF
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'ahale.pdf'
          repo-token: ${{ secrets.GITHUB_TOKEN }}